"""Email templates for result delivery."""

EMAIL_TEMPLATE_HTML = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }}
        .container {{
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            background-color: #4CAF50;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 5px 5px 0 0;
        }}
        .content {{
            background-color: #f9f9f9;
            padding: 20px;
            border-radius: 0 0 5px 5px;
        }}
        .query-box {{
            background-color: white;
            border-left: 4px solid #4CAF50;
            padding: 15px;
            margin: 20px 0;
            font-style: italic;
        }}
        .metrics {{
            display: flex;
            justify-content: space-around;
            margin: 20px 0;
        }}
        .metric {{
            text-align: center;
            padding: 10px;
        }}
        .metric-value {{
            font-size: 24px;
            font-weight: bold;
            color: #4CAF50;
        }}
        .metric-label {{
            font-size: 12px;
            color: #666;
        }}
        .footer {{
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
            color: #666;
        }}
        .button {{
            display: inline-block;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin: 10px 0;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>Query Results Ready</h2>
        </div>
        <div class="content">
            <div class="query-box">
                <strong>Your Query:</strong><br>
                {user_query}
            </div>
            
            <div class="metrics">
                <div class="metric">
                    <div class="metric-value">{row_count}</div>
                    <div class="metric-label">Rows</div>
                </div>
                <div class="metric">
                    <div class="metric-value">{column_count}</div>
                    <div class="metric-label">Columns</div>
                </div>
                <div class="metric">
                    <div class="metric-value">{execution_time}s</div>
                    <div class="metric-label">Execution Time</div>
                </div>
            </div>
            
            <p>Your query has been executed successfully. The results are attached as a CSV file.</p>
            
            {preview_table}
            
            <p style="text-align: center;">
                <a href="{download_url}" class="button">Download Full Results</a>
            </p>
        </div>
        <div class="footer">
            <p>Generated by Agentic RAG Analytics System</p>
            <p>This is an automated email. Please do not reply.</p>
        </div>
    </div>
</body>
</html>
"""

EMAIL_TEMPLATE_PLAIN = """
Query Results Ready
==================

Your Query:
{user_query}

Results:
- Rows: {row_count}
- Columns: {column_count}
- Execution Time: {execution_time}s

Your query has been executed successfully. The results are attached as a CSV file.

Download URL: {download_url}

---
Generated by Agentic RAG Analytics System
This is an automated email. Please do not reply.
"""